### ISSUE TITLE
uninitialized constant JSON::State at /oauth/connect

### ISSUE THREAD

**Issue by srt32** [turadg/pocket-ruby#4]
When I run the demo-server and click on Connect with Pocket from the root path (sending a get to http://localhost:4567/oauth/connect) I see a NameError.  Any idea what I'm doing wrong?  happy holidays! :santa: 

```
OAUTH CONNECT
NameError - uninitialized constant JSON::State:
        /Users/Simon/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/json/common.rb:208:in `generate'
        /Users/Simon/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/json/common.rb:394:in `dump'
        /Users/Simon/.rvm/gems/ruby-2.0.0-p247/gems/faraday_middleware-0.9.0/lib/faraday_middleware/request/encode_json.rb:27:in `encode'
        /Users/Simon/.rvm/gems/ruby-2.0.0-p247/gems/faraday_middleware-0.9.0/lib/faraday_middleware/request/encode_json.rb:21:in `block in call'
        /Users/Simon/.rvm/gems/ruby-2.0.0-p247/gems/faraday_middleware-0.9.0/lib/faraday_middleware/request/encode_json.rb:33:in `match_content_type'
        /Users/Simon/.rvm/gems/ruby-2.0.0-p247/gems/faraday_middleware-0.9.0/lib/faraday_middleware/request/encode_json.rb:20:in `call'
        /Users/Simon/.rvm/gems/ruby-2.0.0-p247/gems/faraday-0.8.8/lib/faraday/response.rb:8:in `call'
        /Users/Simon/Projects/Personal/pocket/pocket_sinatra/lib/faraday/pocket_oauth.rb:15:in `call'
        /Users/Simon/.rvm/gems/ruby-2.0.0-p247/gems/faraday-0.8.8/lib/faraday/connection.rb:253:in `run_request'
        /Users/Simon/.rvm/gems/ruby-2.0.0-p247/gems/faraday-0.8.8/lib/faraday/connection.rb:118:in `post'
        /Users/Simon/Projects/Personal/pocket/pocket_sinatra/lib/pocket/oauth.rb:15:in `get_code'
```

**Comment by jasonngpt** [comment]
Can you try changing the gemspec to point to a newer Sinatra, like 1.3.6? 

I tried to use 2.0.0-p247 (using rbenv) and I am unable to start sinatra 1.3.3. I changed the gemspec to point to another sinatra version (1.3.6) and sinatra manages to start. When I clicked the Connect with Pocket, the Pocket authorisation screen comes up.

I didn't manage to duplicate your error though.

**Comment by srt32** [comment]
Sorry for the delay in responding.  Sinatra 1.3.6 throws the same error and as you said, 1.3.3 won't start.  How are you starting the server?  I'm just using `ruby demo-server.rb`.  Maybe that's my problem?  Thanks.

**Comment by jasonngpt** [comment]
hmmm i am starting the server in the same way as you mentioned.. 

looking at the error again, it seems to be how faraday is interacting with pocket oauth..

maybe u can try to sign out from all existing Pocket sessions in your browser first? and see if the authorisation page from Pocket appears?

**Comment by jasonngpt** [comment]
@srt32 do you have the versions of the faraday and faraday middleware gems you are using?

i am using the below:

faraday - 0.8.8
faraday_middleware - 0.9.0
multi_json - 1.8.2

**Comment by srt32** [comment]
I'm using the same versions you have listed.  I tried logging out of my browser session and got the same error.

**Comment by srt32** [comment]
As you pointed out it's related to faraday and pocket oauth.  I've tracked it down to Faraday::Middleware::PocketOAuth#call on line 15 where it calls `@app.call env`.  It's unclear to me what this part of the code does.  What does `call` on line 15 do there?  Inspecting with pry at this point reveals that env = 

```
=> {:method=>:post,
 :body=>
  {:consumer_key=>"XXX-10188-3565cd04d1464e6d0e64b67f",
   :redirect_uri=>"http://localhost:4567/oauth/callback"},
 :url=>
  #<URI::HTTPS:0x007fe26f903f40 URL:https://getpocket.com/v3/oauth/request>,
 :request_headers=>{"User-Agent"=>"Pocket Ruby Gem 0.0.4"},
 :parallel_manager=>nil,
 :request=>{:proxy=>nil},
 :ssl=>{:verify=>false}}
```

Note, I added 'XXX' to the `consumer_key` to see if I could get a different response but still get the same one.  Does `env` look like what you'd expect?  Thanks for the help.

**Comment by jasonngpt** [comment]
i just tried out from fresh again.. and it works as per expected.. the only difference that is noticeable is rvm vs rbenv (i am using rbenv)

so i was suspecting it could be due to how rvm works with faraday.. i googled it and i found the link https://github.com/colszowka/simplecov/issues/249

try it out.. i think by adding `require json` in the lib/faraday/pocket_oauth.rb should make it to work.. 

anyway the `env` seems ok.. it seems that the error is before the request is sent to Pocket API.. 

hope it works :)

**Comment by jasonngpt** [comment]
hey @srt32 any findings on the `require json` in the lib/faraday/pocket_oauth.rb? maybe i can close this issue if it is ok?

**Comment by srt32** [comment]
@jasonngpt I have not had a chance to get back to it.  Sorry about the delay.  Feel free to close the issue and I will follow up if the issue persists.  Thanks!

**Comment by jasonngpt** [comment]
yup ok.. no worries.. thanks!
